name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to SWTOR-ChatColorManager and thanks for posting your first issue! I will review it ASAP."
        pr-message: "Welcome to SWTOR ChatColorManager and thanks for sharing your first PR! I'll review it as soon as possible and let you know how we can move forward."
