name: Remove Signature and Delete Latest Edit
on:
  issues:
    types:
      - opened
jobs:
  remove_signature_and_delete_edit:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Signature and Delete Latest Edit
        uses: actions/github-script@v5
        with:
          script: |
            const issue = context.payload.issue;
            const description = issue.body.replace(/Sent by \[.*@.*\]/g, '');
            const updatedIssue = await github.rest.issues.update({
              ...context.repo,
              issue_number: issue.number,
              body: description.trim()
            });
            const editHistory = await github.rest.issues.listEvents({
              ...context.repo,
              issue_number: issue.number
            });
            if (editHistory.data.length > 1) {
              const latestEdit = editHistory.data[0];
              await github.rest.issues.deleteComment({
                ...context.repo,
                comment_id: latestEdit.id
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.P_A_T }}
