name: Remove Signature and Delete Revision History
on:
  issues:
    types:
      - opened

jobs:
  remove_signature_and_delete_revision:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Signature
        uses: actions/github-script@v5
        with:
          script: |
            const issue = context.issue();
            const description = issue.body.replace(/Sent by \[.*\]./, '');
            const updatedIssue = await github.issues.update({
              ...context.repo,
              issue_number: issue.number,
              body: description.trim()
            });
            await github.repos.deleteCommitComment({
              ...context.repo,
              comment_id: updatedIssue.data.comments[0].id
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
